apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  labels:
    app: node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: echo-test
        image: demo/node-api:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: BASE_PATH
          value: "/api"
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "20Mi"
            cpu: "100m"
          limits:
            memory: "40Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: node-api
spec:
  selector:
    app: node-api
  ports:
  - port: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localhost-ingress-node-api-minion
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /api
        pathType: ImplementationSpecific
        backend:
          service:
            name: node-api
            port:
              number: 3000
